---
- name: "Install pip packages"
  ansible.builtin.pip:
    name: "{{ item }}"
  loop:
    - ipkyernel
    - bash_kernel

- name: "Install bash kernelspec"
  ansible.builtin.shell: "python -m bash_kernel.install"
