---
- ansible.builtin.pip:
    name: jupyter_core

- ansible.builtin.shell: "jupyter --paths --json"
  register: jupyter_paths

- ansible.builtin.set_fact:
    kernel_virtualenv: "{{ (jupyter_paths.stdout | from_json).data[0] }}/hydra-kernel/venv"

- ansible.builtin.pip:
    name: "{{ item }}"
    virtualenv: "{{ kernel_virtualenv }}"
  loop:
    - ipykernel
    - bash_kernel

- ansible.builtin.shell: "{{ kernel_virtualenv }}/bin/python -m bash_kernel.install"
