---
- name: 'Install pip packages'
  ansible.builtin.pip:
    name: '{{ item }}'
  loop:
    - ipykernel
    - bash_kernel

- name: 'Install bash kernelspec'
  ansible.builtin.shell: 'python -m bash_kernel.install'
